spring:
  application:
    name: gestion-depassement-plafond
  config:
    import:
      - "application_b.yml"
      - "application_hb.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "hb"

file:
  storage:
    path: 'uploads/'

server:
  port: 8088


server1:
  ip: '192.168.11.36'
  path: '/home/afriland/fich_monetique/'
  user: 'afriland'
  password: '@GedIntra2021$'
  nomFichier: 'fichier_monetique.xlsx'
  dossierFichier: 'db/files/'
  port: '21'
  saveData2: 'db/files/'
  output: 'db/output/'
  template: 'templates/'
  nbreApurComexPlaf: 30
  libCirculaire: '004/GR/2022 du 22 juin 2022'
  dureeDelaiApresMiseendemeure: 8
  libDelaiApresMiseendemeure: 'huit'
  lienWhatsapp: 'https://cbl.link/SRLFCJi'
  lienMail: 'justifmonetique@afrilandfirstbank.com'


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
