spring:
  application:
    name: gestion-depassement-plafond

  config:
    activate:
      on-profile: "b"

  r2dbc:
    url: r2dbc:postgresql://localhost:65432/apurement_comex
    username: root
    password: root

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:65432/apurement_comex
    user: root
    password: root
  mail:
    host: 'mail.afrilandfirstbank.cm'
    port: 25
    username: 'ged_test'
    password: 'Afriland@2024'
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 10000
          auth: true
          starttls:
            enable: false