spring:
  application:
    name: gestion-depassement-plafond
  config:
    activate:
      on-profile: "hb"

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/apurement_comex 
    username: postgres
    password:
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/apurement_comex 
    user: postgres
    password:
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "njikidenis@gmail.com"
    password: "fbla vgcn ppdx inuh"
    protocol: smtp
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
